begin transaction isolation level repeatable read read only;
set local time zone 'UTC';
select jsonb_build_object(
 'observed_at', now(),
 'tables',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'name',c.relname,'kind',c.relkind,'rls',c.relrowsecurity,'force',c.relforcerowsecurity,'acl',c.relacl::text) order by n.nspname,c.relname) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','auth','storage') and c.relkind in ('r','p','v')),
 'columns',(select jsonb_agg(jsonb_build_object('schema',table_schema,'table',table_name,'name',column_name,'type',udt_name,'nullable',is_nullable,'default',column_default,'position',ordinal_position) order by table_schema,table_name,ordinal_position) from information_schema.columns where table_schema in ('public','auth','storage')),
 'constraints',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',co.conname,'type',co.contype,'definition',pg_get_constraintdef(co.oid),'validated',co.convalidated) order by n.nspname,c.relname,co.conname) from pg_constraint co join pg_class c on c.oid=co.conrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','auth','storage')),
 'indexes',(select jsonb_agg(jsonb_build_object('schema',schemaname,'table',tablename,'name',indexname,'definition',indexdef) order by schemaname,tablename,indexname) from pg_indexes where schemaname in ('public','auth','storage')),
 'policies',(select jsonb_agg(to_jsonb(p) order by schemaname,tablename,policyname) from pg_policies p where schemaname in ('public','auth','storage')),
 'functions',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'name',p.proname,'args',pg_get_function_identity_arguments(p.oid),'definer',p.prosecdef,'config',p.proconfig,'acl',p.proacl::text,'definition_hash',md5(pg_get_functiondef(p.oid))) order by n.nspname,p.proname,pg_get_function_identity_arguments(p.oid)) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','auth','storage') and p.prokind='f'),
 'triggers',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',t.tgname,'definition',pg_get_triggerdef(t.oid),'enabled',t.tgenabled) order by n.nspname,c.relname,t.tgname) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','auth','storage') and not t.tgisinternal),
 'grants',(select jsonb_agg(to_jsonb(g) order by table_schema,table_name,grantee,privilege_type) from information_schema.role_table_grants g where table_schema in ('public','auth','storage')),
 'schemas',(select jsonb_agg(jsonb_build_object('name',nspname,'acl',nspacl::text) order by nspname) from pg_namespace where nspname in ('public','auth','storage')),
 'extensions',(select jsonb_agg(jsonb_build_object('name',extname,'version',extversion,'schema',n.nspname) order by extname) from pg_extension e join pg_namespace n on n.oid=e.extnamespace),
 'migrations',(select jsonb_agg(jsonb_build_object('name',migration_name,'checksum',checksum,'finished',finished_at is not null,'rolled_back',rolled_back_at is not null) order by migration_name) from public._prisma_migrations),
 'buckets',(select jsonb_agg(jsonb_build_object('name',id,'public',public,'limit',file_size_limit,'mime',allowed_mime_types) order by id) from storage.buckets),
 'storage',(select jsonb_agg(jsonb_build_object('bucket',bucket_id,'path',name,'metadata',metadata,'custom',user_metadata) order by bucket_id,name) from storage.objects),
 'relationships',jsonb_build_object('auth_users',(select count(*) from auth.users),'identities',(select count(*) from auth.identities),'identity_orphans',(select count(*) from auth.identities i left join auth.users u on u.id=i.user_id where u.id is null),'profile_orphans',(select count(*) from public."User" p left join auth.users u on u.id::text=p.id where u.id is null),'auth_without_profile',(select count(*) from auth.users u left join public."User" p on p.id=u.id::text where p.id is null),'password_accounts',(select count(*) from auth.users where encrypted_password is not null and encrypted_password<>''),'confirmed_emails',(select count(*) from auth.users where email_confirmed_at is not null)),
 'pool',jsonb_build_object('max_connections',current_setting('max_connections'),'current_connections',(select count(*) from pg_stat_activity),'active_connections',(select count(*) from pg_stat_activity where state='active'),'db_size',pg_database_size(current_database()))
) as audit;
commit;
