// Keep ranking policy in one place. Scores describe fit, not calibrated probabilities.
export const ranking = {
  weights: {
    intent: 30,
    reciprocal: 25,
    complement: 15,
    interests: 15,
    collaboration: 5,
    semantic: 8,
    freshness: 2,
  },
  profilePageSize: 12,
  teamCandidates: 80,
  maximumReasons: 3,
  feedbackLimit: 4,
  feedbackDays: 30,
  retentionDays: 90,
  embeddingDimensions: 384,
  providerTimeoutMs: 8000,
  workerBatch: 5,
  maxAttempts: 4,
  leaseSeconds: 180,
  profileFreshnessDays: 30,
  inferredWeight: 3,
  posts: {
    maxWeight: 10,
    topicWeight: 4,
    halfLifeDays: 14,
    maxAgeDays: 90,
    recentLimit: 5,
    reasonThreshold: 1,
  },
  feeds: {
    interest: 20,
    skill: 25,
    text: 5,
    inferred: 3,
    semantic: 10,
    freshness: 20,
    freshnessDays: 7,
    engagement: 5,
    eventSoon: 15,
    eventDays: 14,
    overlapCap: 2,
  },
};
export const recommendationsEnabled = () => process.env.RECOMMENDATIONS_ENABLED !== 'false';
