export const degrees = ['B.Tech', 'B.E.', 'BCA', 'MCA', 'BBA', 'MBA', 'M.Tech', 'M.E.', 'PhD'];
export const graduationYears = Array.from({ length: 21 }, (_, index) => 2020 + index);
export const cities = [
  'Ahmedabad',
  'Bengaluru',
  'Bhopal',
  'Bhubaneswar',
  'Chandigarh',
  'Chennai',
  'Coimbatore',
  'Delhi',
  'Gurugram',
  'Guwahati',
  'Hyderabad',
  'Indore',
  'Jaipur',
  'Kochi',
  'Kolkata',
  'Lucknow',
  'Mumbai',
  'Nagpur',
  'Noida',
  'Patna',
  'Pune',
  'Surat',
  'Thiruvananthapuram',
  'Vadodara',
  'Visakhapatnam',
];
export const profileListOptions = {
  skills: [
    'React',
    'JavaScript',
    'TypeScript',
    'Python',
    'Java',
    'C++',
    'UI/UX Design',
    'Figma',
    'Marketing',
    'Content',
    'Data Science',
    'Machine Learning',
    'Public Speaking',
  ],
  interests: [
    'Technology',
    'Design',
    'Startups',
    'Social Impact',
    'Finance',
    'AI',
    'Gaming',
    'Education',
    'Research',
    'Entrepreneurship',
  ],
  domains: [
    'Web Development',
    'App Development',
    'AI/ML',
    'Design',
    'FinTech',
    'EdTech',
    'HealthTech',
    'Social Impact',
    'E-commerce',
  ],
  lookingFor: [
    'Project partners',
    'Hackathon teammates',
    'Co-founders',
    'Research partners',
    'Mentors',
    'Internships',
    'Freelance work',
    'Creative collaborators',
  ],
};
