CREATE TABLE "College" (id text PRIMARY KEY, name text NOT NULL, "shortName" text NOT NULL, city text NOT NULL, state text NOT NULL, country text NOT NULL DEFAULT 'India', aliases text[] NOT NULL DEFAULT '{}', "verifiedDomains" text[] NOT NULL DEFAULT '{}', active boolean NOT NULL DEFAULT true);
CREATE INDEX "College_country_state_city_idx" ON "College" (country,state,city);
CREATE INDEX "College_aliases_idx" ON "College" USING gin(aliases);
CREATE TABLE "TaxonomyAlias" (field text NOT NULL, alias text NOT NULL, label text NOT NULL, PRIMARY KEY(field,alias));
CREATE TABLE "RecommendationSkillLink" (kind text NOT NULL, source text NOT NULL, target text NOT NULL, PRIMARY KEY(kind,source,target));
CREATE TABLE "RecommendationDocument" (kind text NOT NULL CHECK(kind IN ('PROFILE','IDEA','EVENT')), "targetId" text NOT NULL, "sourceHash" text NOT NULL, skills text[] NOT NULL DEFAULT '{}', interests text[] NOT NULL DEFAULT '{}', "lookingFor" text[] NOT NULL DEFAULT '{}', inferred jsonb NOT NULL DEFAULT '{}', embedding double precision[] NOT NULL DEFAULT '{}', "embeddingModel" text NOT NULL DEFAULT '', "updatedAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(kind,"targetId"));
CREATE INDEX "RecommendationDocument_skills_idx" ON "RecommendationDocument" USING gin(skills);
CREATE INDEX "RecommendationDocument_interests_idx" ON "RecommendationDocument" USING gin(interests);
CREATE INDEX "RecommendationDocument_lookingFor_idx" ON "RecommendationDocument" USING gin("lookingFor");
CREATE TABLE "RecommendationJob" (kind text NOT NULL CHECK(kind IN ('PROFILE','IDEA','EVENT')), "targetId" text NOT NULL, version integer NOT NULL DEFAULT 1, attempts integer NOT NULL DEFAULT 0, "availableAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "lockedUntil" timestamp(3), "lockToken" text, "lastError" text, PRIMARY KEY(kind,"targetId"));
CREATE INDEX "RecommendationJob_availableAt_lockedUntil_idx" ON "RecommendationJob" ("availableAt","lockedUntil");
CREATE TABLE "RecommendationInteraction" ("userId" text NOT NULL REFERENCES "User"(id) ON DELETE CASCADE, "targetType" text NOT NULL CHECK("targetType" IN ('PROFILE','IDEA','EVENT')), "targetId" text NOT NULL, action text NOT NULL, day date NOT NULL, "createdAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY("userId","targetType","targetId",action,day));
CREATE INDEX "RecommendationInteraction_userId_targetType_createdAt_idx" ON "RecommendationInteraction" ("userId","targetType","createdAt");
CREATE INDEX "RecommendationInteraction_createdAt_idx" ON "RecommendationInteraction" ("createdAt");
ALTER TABLE "College" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TaxonomyAlias" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RecommendationSkillLink" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RecommendationDocument" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RecommendationJob" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RecommendationInteraction" ENABLE ROW LEVEL SECURITY;
-- No browser policies: the existing trusted Prisma backend owns all access.
CREATE FUNCTION fc_key(value text) RETURNS text LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$ SELECT regexp_replace(lower(trim(value)), '[^a-z0-9]+', '', 'g') $$;
CREATE FUNCTION fc_normalize(field_name text, vals text[]) RETURNS text[] LANGUAGE sql STABLE AS $$
 SELECT COALESCE(array_agg(DISTINCT COALESCE(a.label, trim(v))), '{}') FROM unnest(vals) v LEFT JOIN "TaxonomyAlias" a ON a.field=field_name AND a.alias=fc_key(v) WHERE trim(v)<>''
$$;
CREATE FUNCTION fc_link(link_kind text, vals text[]) RETURNS text[] LANGUAGE sql STABLE AS $$ SELECT COALESCE(array_agg(DISTINCT target),'{}') FROM "RecommendationSkillLink" WHERE kind=link_kind AND source=ANY(vals) $$;
CREATE FUNCTION fc_overlap(a text[], b text[]) RETURNS double precision LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$ SELECT count(DISTINCT v)::double precision FROM unnest(a) v WHERE v=ANY(b) $$;
CREATE FUNCTION fc_cosine(a double precision[], b double precision[]) RETURNS double precision LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
 SELECT CASE WHEN cardinality(a)=cardinality(b) AND cardinality(a)>0 THEN COALESCE(sum(x*y)/NULLIF(sqrt(sum(x*x))*sqrt(sum(y*y)),0),0) ELSE 0 END FROM unnest(a,b) AS v(x,y)
$$;
CREATE FUNCTION fc_college(value text) RETURNS text LANGUAGE sql STABLE AS $$ SELECT COALESCE((SELECT id FROM "College" c WHERE fc_key(c.name)=fc_key(value) OR fc_key(c."shortName")=fc_key(value) OR EXISTS(SELECT 1 FROM unnest(c.aliases) a WHERE fc_key(a)=fc_key(value)) ORDER BY id LIMIT 1),fc_key(value)) $$;
-- Trigger only tracks public recommendation fields. No names, contact URLs or private data.
CREATE FUNCTION fc_enqueue() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE k text; payload jsonb; old_payload jsonb;
BEGIN
 k := CASE TG_TABLE_NAME WHEN 'User' THEN 'PROFILE' WHEN 'Idea' THEN 'IDEA' ELSE 'EVENT' END;
 IF TG_OP='DELETE' THEN
   DELETE FROM "RecommendationDocument" WHERE kind=k AND "targetId"=OLD.id;
   DELETE FROM "RecommendationJob" WHERE kind=k AND "targetId"=OLD.id;
   DELETE FROM "RecommendationInteraction" WHERE "targetType"=k AND "targetId"=OLD.id;
   RETURN OLD;
 END IF;
 IF k='PROFILE' THEN
   payload:=jsonb_build_array(NEW.bio,NEW.skills,NEW.interests,NEW.domains,NEW."lookingFor",NEW.college,NEW.city,NEW."graduationYear");
   IF TG_OP='UPDATE' THEN old_payload:=jsonb_build_array(OLD.bio,OLD.skills,OLD.interests,OLD.domains,OLD."lookingFor",OLD.college,OLD.city,OLD."graduationYear"); END IF;
 ELSIF k='IDEA' THEN
   payload:=jsonb_build_array(NEW.title,NEW.description,NEW.category,NEW.skills,NEW.tags);
   IF TG_OP='UPDATE' THEN old_payload:=jsonb_build_array(OLD.title,OLD.description,OLD.category,OLD.skills,OLD.tags); END IF;
 ELSE
   payload:=jsonb_build_array(NEW.title,NEW.description,NEW.category);
   IF TG_OP='UPDATE' THEN old_payload:=jsonb_build_array(OLD.title,OLD.description,OLD.category); END IF;
 END IF;
 IF payload IS NOT DISTINCT FROM old_payload THEN RETURN NEW; END IF;
 DELETE FROM "RecommendationDocument" WHERE kind=k AND "targetId"=NEW.id;
 INSERT INTO "RecommendationJob"(kind,"targetId") VALUES(k,NEW.id)
 ON CONFLICT(kind,"targetId") DO UPDATE SET version="RecommendationJob".version+1, attempts=0,"availableAt"=CURRENT_TIMESTAMP,"lockedUntil"=NULL,"lockToken"=NULL,"lastError"=NULL;
 RETURN NEW;
END $$;
CREATE TRIGGER fc_profile_changed AFTER INSERT OR UPDATE OR DELETE ON "User" FOR EACH ROW EXECUTE FUNCTION fc_enqueue();
CREATE TRIGGER fc_idea_changed AFTER INSERT OR UPDATE OR DELETE ON "Idea" FOR EACH ROW EXECUTE FUNCTION fc_enqueue();
CREATE TRIGGER fc_event_changed AFTER INSERT OR UPDATE OR DELETE ON "Event" FOR EACH ROW EXECUTE FUNCTION fc_enqueue();
INSERT INTO "RecommendationJob"(kind,"targetId") SELECT 'PROFILE',id FROM "User" UNION ALL SELECT 'IDEA',id FROM "Idea" UNION ALL SELECT 'EVENT',id FROM "Event";
-- Helpers are only for the backend role. No public RPC execution surface.
REVOKE ALL ON FUNCTION fc_key(text),fc_normalize(text,text[]),fc_link(text,text[]),fc_overlap(text[],text[]),fc_cosine(double precision[],double precision[]),fc_college(text),fc_enqueue() FROM PUBLIC;

INSERT INTO "TaxonomyAlias" VALUES ('skills','webdevelopment','Web Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','web','Web Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','webdeveloper','Web Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','react','Web Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','nextjs','Web Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','javascript','Web Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','typescript','Web Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','html','Web Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','css','Web Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','appdevelopment','App Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','appdeveloper','App Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','mobiledevelopment','App Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','flutter','App Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','kotlin','App Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','swift','App Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','android','App Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','ios','App Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','fullstackdevelopment','Full Stack Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','fullstack','Full Stack Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','nodejs','Full Stack Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','django','Full Stack Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','aimachinelearning','AI / Machine Learning') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','ai','AI / Machine Learning') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','ml','AI / Machine Learning') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','aiml','AI / Machine Learning') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','machinelearning','AI / Machine Learning') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','artificialintelligence','AI / Machine Learning') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','datascience','Data Science') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','dataanalysis','Data Science') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','analytics','Data Science') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','cybersecurity','Cybersecurity') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','security','Cybersecurity') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','blockchainweb3','Blockchain / Web3') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','blockchain','Blockchain / Web3') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','web3','Blockchain / Web3') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','gamedevelopment','Game Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','gamedeveloper','Game Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','uiuxdesign','UI/UX Design') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','uiux','UI/UX Design') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','uxdesign','UI/UX Design') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','uidesign','UI/UX Design') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','figma','UI/UX Design') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','graphicdesign','Graphic Design') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','graphicdesigner','Graphic Design') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','productdesign','Product Design') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','productdesigner','Product Design') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','videoediting','Video Editing') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','videoeditor','Video Editing') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','photography','Photography') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','photographer','Photography') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','videography','Videography') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','videographer','Videography') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','contentcreation','Content Creation') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','content','Content Creation') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','contentcreator','Content Creation') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','youtuber','Content Creation') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','youtube','Content Creation') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','writingcopywriting','Writing / Copywriting') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','writing','Writing / Copywriting') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','copywriting','Writing / Copywriting') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','storytelling','Writing / Copywriting') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','socialmedia','Social Media') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','socialmediamanagement','Social Media') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','digitalmarketing','Digital Marketing') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','digitalmarketer','Digital Marketing') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','growthmarketing','Growth & Marketing') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','marketing','Growth & Marketing') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','growth','Growth & Marketing') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','sales','Sales') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','selling','Sales') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','businessdevelopment','Business Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','businessdeveloper','Business Development') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','productmanagement','Product Management') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','productmanager','Product Management') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','finance','Finance') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','financialanalysis','Finance') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','marketresearch','Market Research') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','marketresearcher','Market Research') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','entrepreneurship','Entrepreneurship') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','startupbuilder','Entrepreneurship') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','entrepreneur','Entrepreneurship') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','pitching','Pitching') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','pitch','Pitching') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','publicspeaking','Public Speaking') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','speaking','Public Speaking') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','eventmanagement','Event Management') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','eventorganizer','Event Management') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','eventorganiser','Event Management') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','communitybuilding','Community Building') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','community','Community Building') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','sponsorshipoutreach','Sponsorship & Outreach') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','sponsorship','Sponsorship & Outreach') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','outreach','Sponsorship & Outreach') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','leadership','Leadership') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','teamleadership','Leadership') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','roboticsiot','Robotics / IoT') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','robotics','Robotics / IoT') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','iot','Robotics / IoT') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','hardwareelectronics','Hardware / Electronics') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','hardware','Hardware / Electronics') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','electronics','Hardware / Electronics') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','cad','Hardware / Electronics') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','research','Research') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','researcher','Research') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','filmmaking','Filmmaking') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','filmmaker','Filmmaking') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','acting','Acting') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('skills','actor','Acting') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','startupsentrepreneurship','Startups & Entrepreneurship') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','startups','Startups & Entrepreneurship') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','startup','Startups & Entrepreneurship') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','entrepreneurship','Startups & Entrepreneurship') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','artificialintelligence','Artificial Intelligence') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','ai','Artificial Intelligence') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','ml','Artificial Intelligence') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','machinelearning','Artificial Intelligence') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','aiml','Artificial Intelligence') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','technology','Technology') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','tech','Technology') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','saas','SaaS') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','softwareasaservice','SaaS') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','fintech','FinTech') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','financialtechnology','FinTech') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','edtech','EdTech') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','education','EdTech') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','educationtechnology','EdTech') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','healthtech','HealthTech') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','healthtechnology','HealthTech') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','deeptech','DeepTech') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','web3','Web3') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','blockchain','Web3') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','cybersecurity','Cybersecurity') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','robotics','Robotics') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','iot','Robotics') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','gaming','Gaming') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','games','Gaming') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','esports','Esports') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','design','Design') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','designing','Design') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','product','Product') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','productmanagement','Product') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','marketing','Marketing') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','growth','Marketing') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','financeinvesting','Finance & Investing') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','finance','Finance & Investing') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','investing','Finance & Investing') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','consulting','Consulting') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','consultancy','Consulting') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','contentcreation','Content Creation') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','content','Content Creation') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','youtube','YouTube') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','youtuber','YouTube') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','filmmaking','Filmmaking') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','film','Filmmaking') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','photography','Photography') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','photos','Photography') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','music','Music') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','musician','Music') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','acting','Acting') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','actor','Acting') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','podcasting','Podcasting') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','podcasts','Podcasting') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','writing','Writing') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','copywriting','Writing') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','hackathons','Hackathons') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','hackathon','Hackathons') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','competitiveprogramming','Competitive Programming') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','competitivecoding','Competitive Programming') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','research','Research') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','researching','Research') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','opensource','Open Source') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','socialimpact','Social Impact') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','socialgood','Social Impact') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','sustainability','Sustainability') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','environment','Sustainability') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','ecells','E-Cells') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','ecell','E-Cells') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','collegeevents','College Events') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','campusevents','College Events') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','sports','Sports') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('interests','sport','Sports') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','cofounder','Co-founder') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','cofounders','Co-founder') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','startupteam','Startup Team') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','startupteams','Startup Team') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','hackathonteam','Hackathon Team') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','hackathonteammates','Hackathon Team') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','hackathonteams','Hackathon Team') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','projectteammates','Project Teammates') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','projectpartners','Project Teammates') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','projectteam','Project Teammates') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','webdeveloper','Web Developer') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','webdevelopers','Web Developer') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','appdeveloper','App Developer') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','appdevelopers','App Developer') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','aimldeveloper','AI/ML Developer') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','aideveloper','AI/ML Developer') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','mldeveloper','AI/ML Developer') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','designer','Designer') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','designers','Designer') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','uiuxdesigner','UI/UX Designer') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','uxdesigner','UI/UX Designer') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','videoeditor','Video Editor') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','videoeditors','Video Editor') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','contentcreator','Content Creator') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','contentcreators','Content Creator') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','marketinggrowthpartner','Marketing/Growth Partner') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','marketingpartner','Marketing/Growth Partner') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','growthpartner','Marketing/Growth Partner') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','businesspartner','Business Partner') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','businesspartners','Business Partner') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','researchcollaborator','Research Collaborator') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','researchpartners','Research Collaborator') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','gamingesportsteam','Gaming/Esports Team') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','gamingteam','Gaming/Esports Team') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','esportsteam','Gaming/Esports Team') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','filmcontentteam','Film/Content Team') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','filmteam','Film/Content Team') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','creativecollaborators','Film/Content Team') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','mentor','Mentor') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','mentors','Mentor') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','internshipopportunities','Internship Opportunities') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','internships','Internship Opportunities') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','internship','Internship Opportunities') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','freelancecollaborations','Freelance Collaborations') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','freelancework','Freelance Collaborations') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','freelancing','Freelance Collaborations') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','networking','Networking') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','network','Networking') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','ecellcollaborations','E-Cell Collaborations') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','justexploring','Just Exploring') ON CONFLICT DO NOTHING;
INSERT INTO "TaxonomyAlias" VALUES ('lookingFor','exploring','Just Exploring') ON CONFLICT DO NOTHING;
INSERT INTO "College" VALUES ('lnmiit','The LNM Institute of Information Technology Jaipur','LNMIIT','Jaipur','Rajasthan','India',ARRAY['LNMIIT','The LNM Institute of Information Technology']::text[],'{}',true);
INSERT INTO "College" VALUES ('mnit-jaipur','Malaviya National Institute of Technology Jaipur','MNIT','Jaipur','Rajasthan','India',ARRAY['MNIT','MNIT Jaipur']::text[],'{}',true);
INSERT INTO "College" VALUES ('muj','Manipal University Jaipur','MUJ','Jaipur','Rajasthan','India',ARRAY['MUJ']::text[],'{}',true);
INSERT INTO "College" VALUES ('jecrc-university','JECRC University','JECRC University','Jaipur','Rajasthan','India',ARRAY[]::text[],'{}',true);
INSERT INTO "College" VALUES ('jecrc-foundation','Jaipur Engineering College & Research Centre','JECRC Foundation','Jaipur','Rajasthan','India',ARRAY['JECRC Foundation','JECRC College']::text[],'{}',true);
INSERT INTO "College" VALUES ('nims','NIMS University Rajasthan','NIMS','Jaipur','Rajasthan','India',ARRAY['NIMS','NIMS University']::text[],'{}',true);
INSERT INTO "College" VALUES ('jnu-jaipur','Jaipur National University','JNU Jaipur','Jaipur','Rajasthan','India',ARRAY['JNU Jaipur']::text[],'{}',true);
INSERT INTO "College" VALUES ('amity-rajasthan','Amity University Rajasthan','Amity Jaipur','Jaipur','Rajasthan','India',ARRAY['Amity Jaipur']::text[],'{}',true);
INSERT INTO "College" VALUES ('poornima-university','Poornima University','PU Jaipur','Jaipur','Rajasthan','India',ARRAY['PU Jaipur']::text[],'{}',true);
INSERT INTO "College" VALUES ('poornima-engineering','Poornima College of Engineering','PCE Jaipur','Jaipur','Rajasthan','India',ARRAY['PCE Jaipur']::text[],'{}',true);
INSERT INTO "College" VALUES ('skit','Swami Keshvanand Institute of Technology','SKIT','Jaipur','Rajasthan','India',ARRAY['SKIT','SKIT Jaipur']::text[],'{}',true);
INSERT INTO "College" VALUES ('git-jaipur','Global Institute of Technology Jaipur','GIT Jaipur','Jaipur','Rajasthan','India',ARRAY['GIT Jaipur']::text[],'{}',true);
INSERT INTO "College" VALUES ('rajasthan-university','University of Rajasthan','RU Jaipur','Jaipur','Rajasthan','India',ARRAY['RU Jaipur','Rajasthan University']::text[],'{}',true);
INSERT INTO "College" VALUES ('xaviers-jaipur','St. Xavier''s College Jaipur','Xaviers Jaipur','Jaipur','Rajasthan','India',ARRAY['Xaviers Jaipur']::text[],'{}',true);
INSERT INTO "College" VALUES ('jklu','JK Lakshmipat University','JKLU','Jaipur','Rajasthan','India',ARRAY['JKLU']::text[],'{}',true);
INSERT INTO "College" VALUES ('vgu','Vivekananda Global University','VGU','Jaipur','Rajasthan','India',ARRAY['VGU']::text[],'{}',true);
INSERT INTO "College" VALUES ('apex','Apex University','Apex Jaipur','Jaipur','Rajasthan','India',ARRAY['Apex Jaipur']::text[],'{}',true);
INSERT INTO "College" VALUES ('jagannath-jaipur','Jagannath University Jaipur','Jagannath Jaipur','Jaipur','Rajasthan','India',ARRAY['Jagannath Jaipur']::text[],'{}',true);
INSERT INTO "College" VALUES ('arya','Arya College','Arya Jaipur','Jaipur','Rajasthan','India',ARRAY['Arya Jaipur']::text[],'{}',true);
INSERT INTO "College" VALUES ('subodh','SS Jain Subodh PG College','Subodh College','Jaipur','Rajasthan','India',ARRAY['Subodh College']::text[],'{}',true);
INSERT INTO "College" VALUES ('iis','IIS University','IIS Jaipur','Jaipur','Rajasthan','India',ARRAY['IIS Jaipur']::text[],'{}',true);
INSERT INTO "College" VALUES ('kanoria','Kanoria PG Mahila Mahavidyalaya','Kanoria College','Jaipur','Rajasthan','India',ARRAY['Kanoria College']::text[],'{}',true);
INSERT INTO "College" VALUES ('biyani','Biyani Group of Colleges','Biyani','Jaipur','Rajasthan','India',ARRAY['Biyani']::text[],'{}',true);
INSERT INTO "College" VALUES ('college-of-jaipur','College of Jaipur','College of Jaipur','Jaipur','Rajasthan','India',ARRAY[]::text[],'{}',true);
INSERT INTO "RecommendationSkillLink" VALUES ('intent','Web Developer','Web Development') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','Web Developer','Full Stack Development') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','App Developer','App Development') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','App Developer','Full Stack Development') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','AI/ML Developer','AI / Machine Learning') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','AI/ML Developer','Data Science') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','Designer','UI/UX Design') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','Designer','Graphic Design') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','Designer','Product Design') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','UI/UX Designer','UI/UX Design') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','UI/UX Designer','Product Design') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','Video Editor','Video Editing') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','Content Creator','Content Creation') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','Content Creator','Writing / Copywriting') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','Marketing/Growth Partner','Growth & Marketing') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','Marketing/Growth Partner','Digital Marketing') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','Marketing/Growth Partner','Social Media') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','Business Partner','Business Development') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','Business Partner','Entrepreneurship') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','Business Partner','Finance') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','Research Collaborator','Research') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','Film/Content Team','Filmmaking') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','Film/Content Team','Acting') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','Film/Content Team','Videography') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','Film/Content Team','Video Editing') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','E-Cell Collaborations','Event Management') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','E-Cell Collaborations','Community Building') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('intent','E-Cell Collaborations','Sponsorship & Outreach') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Web Development','UI/UX Design') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','UI/UX Design','Web Development') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','App Development','UI/UX Design') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','UI/UX Design','App Development') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Full Stack Development','Product Design') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Product Design','Full Stack Development') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Web Development','Product Design') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Product Design','Web Development') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Web Development','Growth & Marketing') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Growth & Marketing','Web Development') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Full Stack Development','Growth & Marketing') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Growth & Marketing','Full Stack Development') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','AI / Machine Learning','Web Development') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Web Development','AI / Machine Learning') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','AI / Machine Learning','App Development') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','App Development','AI / Machine Learning') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Content Creation','Video Editing') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Video Editing','Content Creation') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Filmmaking','Acting') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Acting','Filmmaking') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Filmmaking','Videography') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Videography','Filmmaking') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Entrepreneurship','Business Development') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Business Development','Entrepreneurship') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Entrepreneurship','Growth & Marketing') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Growth & Marketing','Entrepreneurship') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Event Management','Sponsorship & Outreach') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Sponsorship & Outreach','Event Management') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Robotics / IoT','AI / Machine Learning') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','AI / Machine Learning','Robotics / IoT') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Hardware / Electronics','Web Development') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Web Development','Hardware / Electronics') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Research','Web Development') ON CONFLICT DO NOTHING;
INSERT INTO "RecommendationSkillLink" VALUES ('complement','Web Development','Research') ON CONFLICT DO NOTHING;
